# Copyright (c) 2024 RFull Development
# This source code is managed under the MIT license. See LICENSE in the project root.
services:
  app:
    image: hello-world:latest
    container_name: hello-world
    restart: none
