# Copyright (c) 2024 RFull Development
# This source code is managed under the MIT license. See LICENSE in the project root.
services:
  develop:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ..:/workspace:cached
